name: Rust

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt
        
    - name: Check formatting
      run: cargo fmt -- --check
      continue-on-error: true

    - name: Run Clippy
      run: cargo clippy -- -D warnings
      continue-on-error: true

    - name: Build
      run: cargo build --verbose
